<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Valuation Report</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.5; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        .header h1 { color: #2563eb; margin: 0; text-transform: uppercase; font-size: 24px; }
        .header p { margin: 5px 0; color: #666; font-size: 12px; }
        .summary-box { background-color: #f8fafc; border-radius: 8px; padding: 20px; margin-bottom: 30px; border: 1px solid #e2e8f0; }
        .summary-grid { display: table; width: 100%; text-align: center; }
        .summary-item { display: table-cell; width: 33%; }
        .summary-label { font-size: 10px; color: #64748b; text-transform: uppercase; font-weight: bold; margin-bottom: 5px; }
        .summary-value { font-size: 20px; color: #0f172a; font-weight: 800; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th { background-color: #f1f5f9; text-align: left; padding: 12px 8px; border-bottom: 2px solid #e2e8f0; color: #475569; }
        td { padding: 10px 8px; border-bottom: 1px solid #f1f5f9; }
        .text-right { text-align: right; }
        .total-row { background-color: #f8fafc; font-weight: bold; }
        .footer { text-align: center; margin-top: 50px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inventory Valuation Report</h1>
        <p>Status as of: {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <div class="summary-box">
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-label">Total Asset Value</div>
                <div class="summary-value">${{ number_format($totalValue, 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Unique Products</div>
                <div class="summary-value">{{ count($products) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Total Stock Units</div>
                <div class="summary-value">{{ number_format($products->sum('total_stock')) }}</div>
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>SKU</th>
                <th>Product Name</th>
                <th>Category</th>
                <th class="text-right">Stock</th>
                <th class="text-right">Avg Cost</th>
                <th class="text-right">Valuation</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
                <tr>
                    <td><code>{{ $product->sku }}</code></td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->category->name ?? 'N/A' }}</td>
                    <td class="text-right">{{ $product->total_stock }} {{ $product->unit->name }}</td>
                    <td class="text-right">${{ number_format($product->cost_price, 2) }}</td>
                    <td class="text-right"><strong>${{ number_format($product->total_stock * $product->cost_price, 2) }}</strong></td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="5" class="text-right">AGGREGATE VALUATION:</td>
                <td class="text-right" style="font-size: 14px; color: #2563eb;">${{ number_format($totalValue, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>Confidential Business Inventory Document</p>
        <p>Generated by {{ Auth::user()->name }} via IMS V2</p>
    </div>
</body>
</html>
