<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Movement Receipt</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.5; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        .header h1 { color: #2563eb; margin: 0; text-transform: uppercase; font-size: 24px; }
        .header p { margin: 5px 0; color: #666; font-size: 12px; }
        .section { margin-bottom: 20px; }
        .section-title { font-weight: bold; border-bottom: 1px solid #eee; margin-bottom: 10px; padding-bottom: 5px; font-size: 14px; color: #2563eb; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f8fafc; text-align: left; padding: 10px; font-size: 12px; border-bottom: 1px solid #edf2f7; }
        td { padding: 10px; border-bottom: 1px solid #edf2f7; font-size: 12px; }
        .footer { text-align: center; margin-top: 50px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        .badge { display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .badge-in { background-color: #dcfce7; color: #166534; }
        .badge-out { background-color: #fee2e2; color: #991b1b; }
        .info-grid { display: table; width: 100%; }
        .info-col { display: table-cell; width: 50%; vertical-align: top; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Stock Movement Receipt</h1>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="section">
        <div class="info-grid">
            <div class="info-col">
                <div class="section-title">Transaction Details</div>
                <p><strong>Reference:</strong> {{ $movement->reference ?? 'N/A' }}</p>
                <p><strong>Type:</strong> <span class="badge {{ $movement->type == 'IN' ? 'badge-in' : 'badge-out' }}">STOCK {{ $movement->type }}</span></p>
                <p><strong>Date:</strong> {{ $movement->created_at->format('Y-m-d H:i:s') }}</p>
            </div>
            <div class="info-col text-right">
                <div class="section-title">Warehouse Hub</div>
                <p><strong>Location:</strong> {{ $movement->warehouse->name ?? 'Primary Center' }}</p>
                <p><strong>Address:</strong> {{ $movement->warehouse->location ?? 'Global Distribution' }}</p>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Items Processed</div>
        <table>
            <thead>
                <tr>
                    <th>Product SKU</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $movement->product->sku }}</td>
                    <td>{{ $movement->product->name }}</td>
                    <td><strong>{{ $movement->quantity }}</strong></td>
                    <td>{{ $movement->product->unit->name }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">System Authorization</div>
        <p><strong>Processed By:</strong> {{ $movement->user->name }} ({{ $movement->user->email }})</p>
        <p><strong>Audit UID:</strong> #{{ str_pad($movement->id, 8, '0', STR_PAD_LEFT) }}</p>
    </div>

    <div class="footer">
        <p>This is an automated document generated by Inventory System V2.</p>
        <p>&copy; {{ date('Y') }} Enterprise Inventory Management.</p>
    </div>
</body>
</html>
